version: '3.3'

services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    image: maistodos-creditcard
    ports:
      - 8000:8000
    volumes:
      - .:/home/python/app
    restart: always