version: '3.3'

services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    image: maistodos-creditcard
    ports:
      - 8000:8000
    volumes:
      - .:/home/python/app
    restart: always
    networks:
      - maistodos
  database:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - 'database:/var/lib/postgresql/data'
    networks:
      - maistodos
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - 5050:80
    depends_on:
      - database
networks:
    maistodos:
        driver: bridge
volumes:
  database:
    driver: local